name: 👽 Atmos Release

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # required to get the previous release SHA

jobs:
  affected:
    name: Trigger Affected

    runs-on:
      - "ubuntu-latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # TODO replace this placeholder action with the true API call
      # to get this value from the atmos pro app
      - name: Get latest release commit SHA
        id: get_latest_release_sha
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Getting last 2 releases. This release and the previous..."
          latest_release_tag=$(gh release list --limit 2 --json tagName --jq '.[1].tagName')
          echo "Getting the SHA of the previous release..."
          commit_sha=$(gh api repos/${{ github.repository }}/git/ref/tags/$latest_release_tag --jq '.object.sha')
          echo "commit_sha=$commit_sha" >> $GITHUB_OUTPUT

      - name: Gather Affected Stacks
        id: affected
        uses: cloudposse/github-action-atmos-affected-stacks@v3
        env:
          ATMOS_PRO_TOKEN: ${{ secrets.ATMOS_PRO_TOKEN }}
          ATMOS_PRO_BASE_URL: ${{ vars.ATMOS_PRO_BASE_URL }}
        with:
          atmos-version: ${{ vars.ATMOS_VERSION }}
          atmos-config-path: ${{ vars.ATMOS_CONFIG_PATH }}
          atmos-pro-upload: true
          atmos-pro-token: ${{ secrets.ATMOS_PRO_TOKEN }}
          atmos-pro-base-url: ${{ vars.ATMOS_PRO_BASE_URL }}
          base-ref: ${{ steps.get_latest_release_sha.outputs.commit_sha }}
          head-ref: ${{ github.sha  }}
