name: 👽 Atmos Preview

on:
  #pull_request_target:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  affected:
    name: Trigger Affected

    runs-on:
      - "ubuntu-latest"

    steps:
      - name: Gather Affected Stacks
        id: affected
        uses: cloudposse/github-action-atmos-affected-stacks@v3
        with:
          atmos-version: ${{ vars.ATMOS_VERSION }}
          atmos-config-path: ${{ vars.ATMOS_CONFIG_PATH }}
          atmos-pro-upload: true
          atmos-pro-token: ${{ secrets.ATMOS_PRO_TOKEN }}
          atmos-pro-base-url: ${{ vars.ATMOS_PRO_BASE_URL }}
          head-ref: ${{ github.event.pull_request.head.sha }}
